# https://taskfile.dev

version: "3"

interval: "500ms"

tasks:
  bump:
    vars:
      VERSION: "0.0.20241015"
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push origin v{{.VERSION}}
      - GOPROXY=proxy.golang.org go list -m github.com/delaneyj/gomponents-iconify@v{{.VERSION}}

  default:
    sources:
      - "**/*.json"
      - "**/*.go"
    generates:
      - iconify/**/*
    cmds:
      - rm -rf iconify
      - rm -rf gentmp
      - go run internal/main.go
      - go fmt ./...
