# https://taskfile.dev

version: "3"

interval: "500ms"

tasks:
  default:
    sources:
      - "**/*.json"
      - "**/*.go"
    generates:
      - iconify/**/*
    cmds:
      - rm -rf iconify
      - rm -rf gentmp
      - go run internal/main.go
